import { Check, Download, FileText, Mail, Printer } from "lucide-react";
import type { Candidate, Company, Offer } from "../lib/types";
import { fmtDate, fmtINR } from "../lib/types";
import { useStore } from "../lib/store";
import { Button, Modal, LogoMark } from "./ui";

export function OfferPaper({ company, candidate }: { company: Company; candidate: Candidate }) {
  const offer = candidate.offer;
  if (!offer) return null;
  return (
    <div className="letter-paper rounded-lg p-8 sm:p-10 text-[13.5px] leading-relaxed max-w-[720px] mx-auto" id="offer-paper">
      {/* Letterhead */}
      <div className="flex items-start justify-between pb-6 border-b-2 border-[#2b4ed6]">
        <div className="flex items-center gap-3">
          <LogoMark size={40} />
          <div>
            <p className="font-display font-bold text-[18px] text-[#101a40] leading-tight">{company.name}</p>
            <p className="text-[11.5px] text-[#5a688c]">{company.address}</p>
            <p className="text-[11.5px] text-[#5a688c]">{company.website} · {company.contactEmail}</p>
          </div>
        </div>
        <div className="text-right text-[11.5px] text-[#5a688c]">
          <p className="font-bold text-[#101a40]">Ref: {offer.number}</p>
          <p>Date: {fmtDate(offer.generatedAt)}</p>
        </div>
      </div>

      <div className="mt-6">
        <p className="font-semibold">To,</p>
        <p className="font-bold text-[15px] text-[#101a40]">{candidate.name}</p>
        <p className="text-[#5a688c]">{candidate.email} · {candidate.phone}</p>
      </div>

      <p className="mt-6 font-display font-bold text-[17px] text-[#101a40] tracking-tight">Subject: Offer of Employment — {candidate.position}</p>

      <p className="mt-4">
        Dear <span className="font-semibold">{candidate.name}</span>,
      </p>
      <p className="mt-3">
        Congratulations! Following your successful selection process, we are delighted to offer you the position of{" "}
        <span className="font-semibold">{candidate.position}</span> in our <span className="font-semibold">{candidate.department}</span> department at{" "}
        <span className="font-semibold">{company.name}</span>. We were impressed by your skills and experience, and we believe you will be a valuable addition to our team.
      </p>

      <div className="mt-5 rounded-lg ring-1 ring-[#d3daea] overflow-hidden">
        <table className="w-full text-[13px]">
          <tbody>
            {[
              ["Position", candidate.position],
              ["Department", candidate.department],
              ["Annual Compensation", `${fmtINR(candidate.salary)} (per annum)`],
              ["Date of Joining", fmtDate(candidate.joiningDate)],
              ["Reporting Manager", candidate.reportingManager],
              ["Work Location", company.address.split(",").slice(-2).join(",").trim()],
            ].map(([k, v], i) => (
              <tr key={k} className={i % 2 ? "bg-[#f2f5fc]" : "bg-white"}>
                <td className="px-4 py-2.5 font-semibold text-[#39425c] w-[38%]">{k}</td>
                <td className="px-4 py-2.5 text-[#1c2438] font-medium">{v}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <p className="mt-5 font-semibold text-[#101a40]">Terms & Conditions</p>
      <ol className="mt-2 list-decimal pl-5 space-y-1.5 text-[#39425c]">
        {company.settings.terms.map((t, i) => <li key={i}>{t}</li>)}
      </ol>

      <p className="mt-5">
        Please confirm your acceptance of this offer within <span className="font-semibold">seven (7) days</span> by clicking “Accept Offer” in your secure onboarding portal. A detailed appointment letter will be issued on your date of joining.
      </p>
      <p className="mt-4">We look forward to welcoming you aboard.</p>

      <div className="mt-8 flex items-end justify-between">
        <div>
          <p className="text-[12px] text-[#5a688c]">Warm regards,</p>
          <p className="font-display italic text-[22px] text-[#2b4ed6] mt-1" style={{ fontFamily: "'Space Grotesk', cursive" }}>{company.settings.hrName}</p>
          <div className="mt-1 pt-2 border-t border-[#d3daea] inline-block pr-10">
            <p className="font-bold text-[#101a40] text-[13px]">{company.settings.hrName}</p>
            <p className="text-[11.5px] text-[#5a688c]">{company.settings.hrDesignation}, {company.name}</p>
          </div>
        </div>
        <div className="text-right">
          <span className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-emerald-50 ring-1 ring-emerald-200 text-emerald-700 text-[11px] font-bold">
            <Check size={12} /> Digitally signed & verified
          </span>
          <p className="text-[10.5px] text-[#8a94ad] mt-1.5">{company.name} · Generated by OfferFlow AI</p>
        </div>
      </div>
    </div>
  );
}

export function OfferLetterModal({ candidate, open, onClose }: { candidate: Candidate | null; open: boolean; onClose: () => void }) {
  const { db } = useStore();
  const company = candidate ? db.companies.find((c) => c.id === candidate.companyId) : null;
  if (!candidate || !company) return null;
  return (
    <Modal open={open} onClose={onClose} title={`Offer Letter — ${candidate.offer?.number ?? ""}`} subtitle={`${candidate.name} · ${candidate.position}`} width="max-w-3xl"
      footer={
        <>
          <Button variant="outline" icon={<Printer size={15} />} onClick={() => window.print()}>Download PDF</Button>
          <Button icon={<Check size={15} />} onClick={onClose}>Done</Button>
        </>
      }
    >
      <div className="print-root bg-ink-100/60 dark:bg-ink-925 rounded-xl p-3 sm:p-5 -m-1">
        <OfferPaper company={company} candidate={candidate} />
      </div>
    </Modal>
  );
}

export function OfferEmailModal({ candidate, open, onClose, onViewLetter }: { candidate: Candidate | null; open: boolean; onClose: () => void; onViewLetter: () => void }) {
  const { db } = useStore();
  const company = candidate ? db.companies.find((c) => c.id === candidate.companyId) : null;
  if (!candidate || !company) return null;
  return (
    <Modal open={open} onClose={onClose} title="Offer email preview" subtitle="Exactly what the candidate receives in their inbox" width="max-w-2xl">
      <div className="rounded-xl ring-1 ring-ink-900/10 dark:ring-white/10 overflow-hidden">
        <div className="px-5 py-4 bg-ink-50 dark:bg-ink-925 border-b border-ink-900/8 dark:border-white/8 space-y-1 text-[13px]">
          <p><span className="text-ink-400 font-medium">From:</span> <span className="font-semibold">{company.settings.senderName}</span> &lt;{company.settings.senderEmail}&gt;</p>
          <p><span className="text-ink-400 font-medium">To:</span> {candidate.name} &lt;{candidate.email}&gt;</p>
          <p><span className="text-ink-400 font-medium">Subject:</span> <span className="font-bold text-ink-900 dark:text-white">{company.settings.offerSubject.split("{{CompanyName}}").join(company.name)}</span></p>
        </div>
        <div className="px-5 py-5 bg-white dark:bg-ink-900">
          <p className="whitespace-pre-line text-[13.5px] leading-relaxed text-ink-700 dark:text-ink-200">
            {`Dear ${candidate.name},\n\nCongratulations! We are pleased to offer you the position of ${candidate.position} at ${company.name}.\n\nPlease find your offer letter attached.`}
          </p>
          <button onClick={onViewLetter} className="mt-5 w-full sm:w-auto inline-flex items-center gap-2.5 px-4 py-3 rounded-lg bg-ink-50 dark:bg-ink-925 ring-1 ring-ink-900/10 dark:ring-white/12 hover:ring-cobalt-400 transition-colors group">
            <span className="w-9 h-9 rounded-lg bg-rose-500/12 text-rose-600 dark:text-rose-400 flex items-center justify-center"><FileText size={17} /></span>
            <span className="text-left">
              <span className="block text-[13px] font-bold text-ink-900 dark:text-white group-hover:text-cobalt-600 dark:group-hover:text-cobalt-300 transition-colors">{candidate.offer?.number}_Offer_Letter.pdf</span>
              <span className="block text-[11.5px] text-ink-400">Offer letter · generated automatically</span>
            </span>
          </button>
          <div className="mt-5 flex gap-3">
            <Button size="sm" icon={<FileText size={14} />} onClick={onViewLetter}>View Offer Letter</Button>
            <Button size="sm" variant="outline" icon={<Download size={14} />} onClick={() => window.print()}>Download Offer Letter</Button>
          </div>
        </div>
      </div>
      <p className="mt-3 text-[12px] text-ink-400 flex items-center gap-1.5"><Mail size={13} /> Sent automatically via {company.settings.senderEmail} — delivery simulated in this demo.</p>
    </Modal>
  );
}

const TRACK_STEPS: { key: string; label: string; date: (o: Offer) => string | undefined }[] = [
  { key: "generated", label: "Generated", date: (o) => o.generatedAt },
  { key: "sent", label: "Sent", date: (o) => o.sentAt },
  { key: "viewed", label: "Viewed", date: (o) => o.viewedAt },
];

export function OfferTrack({ offer }: { offer: Offer }) {
  const reached = (key: string) => {
    const order = ["generated", "sent", "viewed", "accepted", "rejected"];
    if (offer.status === "rejected" && key === "viewed") return !!offer.viewedAt;
    return order.indexOf(offer.status) >= order.indexOf(key);
  };
  return (
    <div className="flex items-center gap-1.5 flex-wrap">
      {TRACK_STEPS.map((s, i) => {
        const on = reached(s.key);
        return (
          <span key={s.key} className="flex items-center gap-1.5">
            {i > 0 && <span className={`w-4 h-px ${on ? "bg-cobalt-400" : "bg-ink-300/60 dark:bg-white/15"}`} />}
            <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[11px] font-bold ring-1 ring-inset ${on ? "bg-cobalt-500/10 text-cobalt-700 dark:text-cobalt-300 ring-cobalt-500/25" : "bg-ink-900/4 dark:bg-white/5 text-ink-400 ring-ink-900/10 dark:ring-white/10"}`}>
              {on && <Check size={11} />}
              {s.label}
            </span>
          </span>
        );
      })}
      {offer.status === "accepted" && <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[11px] font-bold bg-emerald-500/10 text-emerald-700 dark:text-emerald-300 ring-1 ring-inset ring-emerald-500/25"><Check size={11} /> Accepted {fmtDate(offer.respondedAt)}</span>}
      {offer.status === "rejected" && <span className="px-2 py-0.5 rounded-full text-[11px] font-bold bg-rose-500/10 text-rose-700 dark:text-rose-300 ring-1 ring-inset ring-rose-500/25">Rejected {fmtDate(offer.respondedAt)}</span>}
    </div>
  );
}
